name: Playwright with docker

on: workflow_dispatch

jobs:
  playwright:
    name: "Playwright Tests with docker"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal
    steps:
      - uses: actions/checkout@v2

      - name: Fix file permissions
        run: |
          chmod -c -R +rX $GITHUB_WORKSPACE
          find $GITHUB_WORKSPACE -type d -exec chmod 755 {} \;
          find $GITHUB_WORKSPACE -type f -exec chmod 644 {} \;

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run your tests
        run: npx playwright test --reporter=html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report/
          publish_branch: gh-pages
          force_orphan: true
