name: Playwright with docker

on: workflow_dispatch

jobs:
  playwright:
    name: "Playwright Tests with docker"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test --reporter=line
      - name: Publish HTML report to testresults.marcusfelling.com
        if: always() # We want this to always run, even if test fail prior to this step running
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report/ # This is where index.html will be output
          keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
          user_name: "github-actions[bot]" # This will be the username that gets stamped in the repo commit
          user_email: "github-actions[bot]@users.noreply.github.com" # This will be the user email that gets stamped in the repo commit
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: test-result
